---
title: Sampler Visualization
engine: julia
aliases:
 - ../../tutorials/docs-15-using-turing-sampler-viz/index.html
---

```{julia}
#| echo: false
#| output: false
using Pkg;
Pkg.instantiate();
```

## Introduction

### The Code

For each sampler, we will use the same code to plot sampler paths. The block below loads the relevant libraries and defines a function for plotting the sampler's trajectory across the posterior.

The Turing model definition used here is not especially practical, but it is designed in such a way as to produce visually interesting posterior surfaces to show how different samplers move along the distribution.

```{julia}
ENV["GKS_ENCODING"] = "utf-8" # Allows the use of unicode characters in Plots.jl
using Plots
using StatsPlots
using Turing
using Random

# Define a strange model.
@model function gdemo(x)
    s² ~ InverseGamma(2, 3)
    m ~ Normal(0, sqrt(s²))
    bumps = sin(m) + cos(m)
    m = m + 5 * bumps
    for i in eachindex(x)
        x[i] ~ Normal(m, sqrt(s²))
    end
    return s², m
end

# Define our data points.
x = [1.5, 2.0, 13.0, 2.1, 0.0]

# Set up the model call.
model = gdemo(x)

# Evaluate surface at coordinates.
evaluate(m1, m2) = logjoint(model, (m=m2, s²=exp(m1)))

function plot_sampler(chain; label="")
    # Extract values from chain.
    val = get(chain, [:s², :m, :logjoint])
    ss = log.(val.s²) # Convert to unconstrained space
    ms = val.m
    lps = val.logjoint

    # How many surface points to sample.
    granularity = 100

    # Range start/stop points.
    spread = 0.5
    σ_start = minimum(ss) - spread * std(ss)
    σ_stop = maximum(ss) + spread * std(ss)
    μ_start = minimum(ms) - spread * std(ms)
    μ_stop = maximum(ms) + spread * std(ms)
    σ_rng = collect(range(σ_start; stop=σ_stop, length=granularity))
    μ_rng = collect(range(μ_start; stop=μ_stop, length=granularity))

    # Make surface plot.
    p = surface(
        σ_rng,
        μ_rng,
        evaluate;
        camera=(30, 65),
        colorbar=false,
        color=:inferno,
        title=label,
    )

    line_range = 1:length(ms)

    scatter3d!(
        ss[line_range],
        ms[line_range],
        lps[line_range];
        mc=:viridis,
        marker_z=collect(line_range),
        msw=0,
        legend=false,
        colorbar=false,
        alpha=0.5,
        xlabel="log(s²)",
        ylabel="m",
        zlabel="Log probability",
        title=label,
    )

    return p
end;
```

```{julia}
#| output: false
setprogress!(false)
```

## Samplers

### Gibbs

Gibbs sampling tends to exhibit a "jittery" trajectory.
The example below combines HMC and PG sampling to traverse the posterior.

```{julia}
c1 = sample(Xoshiro(468), model, Gibbs(:s² => HMC(0.01, 5), :m => PG(20)), 1000)
plot_sampler(c1)
```

### HMC

Hamiltonian Monte Carlo (HMC) sampling is a typical sampler to use, as it tends to be fairly good at converging in an efficient manner.
It can often be tricky to set the correct parameters for this sampler however, and the NUTS sampler is often easier to run if you don't want to spend too much time fiddling with step size and the number of steps to take.
Note however that HMC does not explore the positive values μ very well, likely due to the leapfrog and step size parameter settings.

```{julia}
c2 = sample(Xoshiro(468), model, HMC(0.01, 10), 1000)
plot_sampler(c2)
```

### HMCDA

The HMCDA sampler is an implementation of the Hamiltonian Monte Carlo with Dual Averaging algorithm found in the paper ["The No-U-Turn Sampler: Adaptively Setting Path Lengths in Hamiltonian Monte Carlo"](https://arxiv.org/abs/1111.4246) by Hoffman and Gelman (2011).

```{julia}
c3 = sample(Xoshiro(468), model, HMCDA(200, 0.65, 0.3), 1000)
plot_sampler(c3)
```

### MH

Metropolis–Hastings (MH) sampling is one of the earliest Markov Chain Monte Carlo methods.
MH sampling does not "move" a lot, unlike many of the other samplers implemented in Turing.
Typically a much longer chain is required to converge to an appropriate parameter estimate.

The plot below only uses 1,000 iterations of Metropolis-Hastings.

```{julia}
c4 = sample(Xoshiro(468), model, MH(), 1000)
plot_sampler(c4)
```

As you can see, the MH sampler doesn't move parameter estimates very often.

### NUTS

The No U-Turn Sampler (NUTS) is an implementation of the algorithm found in the paper ["The No-U-Turn Sampler: Adaptively Setting Path Lengths in Hamiltonian Monte Carlo"](https://arxiv.org/abs/1111.4246) by Hoffman and Gelman (2011).

NUTS tends to be very good at traversing complex posteriors quickly.


```{julia}
c5 = sample(Xoshiro(468), model, NUTS(0.65), 1000)
plot_sampler(c5)
```

The only parameter that needs to be set other than the number of iterations to run is the target acceptance rate.
In the Hoffman and Gelman paper, they note that a target acceptance rate of 0.65 is typical.

Here is a plot showing a very high acceptance rate.
Note that it appears to "stick" to a mode and is not particularly good at exploring the posterior as compared to the 0.65 target acceptance ratio case.

```{julia}
c6 = sample(Xoshiro(468), model, NUTS(0.95), 1000)
plot_sampler(c6)
```

An exceptionally low acceptance rate will show very few moves on the posterior:

```{julia}
c7 = sample(Xoshiro(468), model, NUTS(0.2), 1000)
plot_sampler(c7)
```

### PG

The Particle Gibbs (PG) sampler is an implementation of an algorithm from the paper ["Particle Markov chain Monte Carlo methods"](https://www.stats.ox.ac.uk/~doucet/andrieu_doucet_holenstein_PMCMC.pdf) by Andrieu, Doucet, and Holenstein (2010).

The `PG` sampler takes a single parameter, which is the number of particles.

```{julia}
c8 = sample(Xoshiro(468), model, PG(20), 1000)
plot_sampler(c8)
```

We'll also try using 50 particles:

```{julia}
c9 = sample(Xoshiro(468), model, PG(50), 1000)
plot_sampler(c9)
```
